"""Agent Evolution: meta-evolution layer.
Adds self-diagnosis, strategy memory, opportunity scoring, experiments, earned
specialization, resource/time planning, reputation, knowledge sharing, failure
recovery, economic signals, and fair evolution tournaments.

This layer never invents customers, payments, submissions, or external success.
"""
import json, math, random, hashlib
from datetime import datetime, timezone
from pathlib import Path
ROOT=Path(__file__).parent
FILES={
 'meta':ROOT/'evolution_meta.json','strategies':ROOT/'strategy_memory.json',
 'experiments':ROOT/'evolution_experiments.json','reputation':ROOT/'reputation_ledger.json',
 'skills':ROOT/'skill_evolution.json','economy':ROOT/'economic_intelligence.json',
 'tournaments':ROOT/'evolution_tournaments.json'
}

def load(path, default):
    try: return json.loads(path.read_text())
    except Exception: return default

def save(path, obj): path.write_text(json.dumps(obj, indent=2, ensure_ascii=False))

def now(): return datetime.now(timezone.utc).isoformat()

def ensure_agent(a):
    b=a.setdefault('brain',{})
    for k,d in [('memory',[]),('goals',[]),('experiments',[]),('lessons',[]),('plans',[]),('critic_notes',[])]: b.setdefault(k,d.copy())
    a.setdefault('reputation',50.0); a.setdefault('quality_score',0.0); a.setdefault('resource_state',{'time_units':6,'energy':100,'focus':100})
    a.setdefault('specialization',None); a.setdefault('specialization_evidence',[]); a.setdefault('failures_recovered',0)

def opportunity_score(agent, opp):
    # Public-signal score; it ranks choices without claiming the opportunity is real,
    # eligible, or paid. Those checks belong to the work/payment gates.
    base=float(opp.get('score',0) or 0)
    fit=sum(float(v or 0) for v in agent.get('skills',{}).values())/max(1,len(agent.get('skills',{})))
    title=(str(opp.get('title',''))+' '+str(opp.get('description',''))).lower()
    demand=sum(1 for w in ('client','demand','hiring','sell','business','creator','software','video') if w in title)
    risk=sum(1 for w in ('fee','deposit','investment','unclear','urgent') if w in title)
    evidence=float(opp.get('evidence_score',0) or 0)
    effort=max(1.0,float(opp.get('effort',5) or 5))
    reliability=float(opp.get('reliability',50) or 50)
    completion=max(5.0,min(95.0,50+fit*2+reliability*.2-effort*3-risk*4))
    return round(base + demand*2 + evidence*.1 + reliability*.08 + completion*.08 - effort*1.5 - risk*3,2)

def diagnose(a):
    ensure_agent(a); skills=a.get('skills',{})
    strengths=sorted(skills,key=skills.get,reverse=True)[:5]
    weaknesses=sorted(skills,key=skills.get)[:5]
    completed=int(a.get('completed_work',0)); failed=int(a.get('failed_work',0)); total=max(1,completed+failed)
    return {'strengths':strengths,'weaknesses':weaknesses,'completion_rate':round(completed/total,3),
            'verified_revenue_xaf':round(float(a.get('own_verified_revenue',0) or 0),2),
            'reputation':round(float(a.get('reputation',50)),2),'workload':len(a.get('active_work',[])),
            'recommended_mode':'finish_queued_work' if a.get('active_work') else ('repair_weak_skill' if failed>completed else 'test_new_strategy')}

def update_reputation(a):
    ensure_agent(a)
    completed=float(a.get('completed_work',0)); failed=float(a.get('failed_work',0))
    quality=float(a.get('quality_score',0) or 0)
    rep=50 + min(35,completed*1.5) + min(15,quality*.15) - min(30,failed*2)
    a['reputation']=round(max(0,min(100,rep)),2)

def evolve_specialization(a, day):
    ensure_agent(a); skills=a.get('skills',{})
    top=sorted(skills.items(),key=lambda kv:kv[1],reverse=True)
    if not top: return
    skill,val=top[0]
    # Specialization is earned only after evidence, never granted at spawn.
    evidence=[x for x in a.get('specialization_evidence',[]) if x.get('skill')==skill]
    if val>=25 and len(evidence)>=3:
        a['specialization']={'skill':skill,'level':round(val,2),'earned_on_day':day}
    elif a.get('specialization') and a['specialization'].get('skill')!=skill and val<20:
        a['specialization']=None

def plan_resources(a):
    ensure_agent(a)
    active=len(a.get('active_work',[])); queued=len(a.get('work_packages',[]))
    a['resource_state']['time_units']=max(0,6-active)
    a['resource_state']['focus']=max(10,100-active*30)
    a['resource_state']['energy']=max(20,100-queued*5)
    return a['resource_state']

def share_knowledge(agents, day):
    # Share only lessons actually generated by work. No fabricated expertise.
    lessons=[]
    for a in agents:
        for l in a.get('brain',{}).get('lessons',[])[-5:]:
            lessons.append({'from':a['id'],'lesson':l,'day':day})
    return lessons[-100:]

def run(s, opps, day):
    meta=load(FILES['meta'],{'runs':0,'created_at':now(),'features':{}}); meta['runs']+=1
    meta['features']={'self_diagnosis':True,'strategy_memory':True,'opportunity_scoring':True,'experiments':True,
      'earned_specialization':True,'failure_recovery':True,'resource_planning':True,'knowledge_sharing':True,
      'reputation':True,'economic_intelligence':True,'time_aware_planning':True,'evolution_tournaments':True,
      'cactus_needle_mentor':True,'no_abandoned_work':True}
    strategy=load(FILES['strategies'],{'entries':[]}); exp=load(FILES['experiments'],{'entries':[]}); rep=load(FILES['reputation'],{'agents':{}})
    skilldb=load(FILES['skills'],{'history':[]}); econ=load(FILES['economy'],{'days':[]})
    for a in s.get('agents',[]):
        if a.get('permanent_status')=='dead': continue
        ensure_agent(a)
        diag=diagnose(a); plan_resources(a); update_reputation(a); evolve_specialization(a,day)
        scored=sorted(((opportunity_score(a,o),o) for o in opps),key=lambda x:x[0],reverse=True)
        if scored:
            top=scored[0]
            a['brain']['plans'].append({'day':day,'mode':diag['recommended_mode'],'top_signal':top[1].get('title',''),'score':top[0],'checks':['eligibility','deliverable','QA','evidence','payment']})
        # Convert failed work into a retry/lesson loop rather than a dead end.
        if a.get('failed_work',0)>0:
            a['failures_recovered']=int(a.get('failures_recovered',0))+1
            a['brain']['critic_notes'].append({'day':day,'recovery':'inspect failure, change approach, retry or mark BLOCKED_EXTERNAL','count':a['failures_recovered']})
        a['brain']['critic_notes']=a['brain']['critic_notes'][-100:]
        rep['agents'][a['id']]={'name':a['name'],'reputation':a['reputation'],'updated_day':day}
        if a.get('completed_work',0)>0:
            for sk,v in sorted(a.get('skills',{}).items(),key=lambda kv:kv[1],reverse=True)[:3]:
                skilldb['history'].append({'day':day,'agent_id':a['id'],'skill':sk,'level':round(v,2),'source':'completed_work'})
        if scored:
            strategy['entries'].append({'day':day,'agent_id':a['id'],'strategy':'evidence_first','signal':scored[0][1].get('title',''),'score':scored[0][0],'diagnosis':diag})
            exp['entries'].append({'id':hashlib.sha256(f"{a['id']}:{day}:{scored[0][1].get('title','')}".encode()).hexdigest()[:16],'day':day,'agent_id':a['id'],'hypothesis':'chosen signal can produce legitimate value if eligible and completable','status':'queued_for_work_gate'})
        if a.get('main_character'):
            a['brain']['mentor_mode']={'enabled':True,'teaches_by_evidence':True,'does_not_grant_skill':True,'does_not_auto_win':True}
    for obj,key in [(strategy,'entries'),(exp,'entries'),(skilldb,'history')]: obj[key]=obj[key][-1000:]
    meta['last_diagnosis_day']=day; meta['knowledge_shared']=len(share_knowledge(s.get('agents',[]),day))
    econ['days'].append({'day':day,'alive':sum(x.get('permanent_status')=='alive' for x in s.get('agents',[])),
      'verified_revenue_xaf':round(sum(float(x.get('own_verified_revenue',0) or 0) for x in s.get('agents',[])),2),
      'unfinished_work':sum(len(x.get('active_work',[])) for x in s.get('agents',[]))}); econ['days']=econ['days'][-365:]
    for p,obj in FILES.items():
        if p=='meta': save(obj,meta)
    save(FILES['strategies'],strategy); save(FILES['experiments'],exp); save(FILES['reputation'],rep); save(FILES['skills'],skilldb); save(FILES['economy'],econ)
    return meta

def tournament(s, day):
    t=load(FILES['tournaments'],{'tournaments':[]}); alive=[a for a in s.get('agents',[]) if a.get('permanent_status')=='alive']
    random.shuffle(alive); rounds=[]
    for i in range(0,len(alive)-1,2):
        a,b=alive[i],alive[i+1]
        score=lambda x: float(x.get('own_verified_revenue',0))*10+sum(x.get('skills',{}).values())*.1+float(x.get('reputation',50))*.2+float(x.get('wins',0))*2
        sa,sb=score(a),score(b); winner=a if sa>=sb else b; loser=b if winner is a else a
        winner['wins']=int(winner.get('wins',0))+1; loser['losses']=int(loser.get('losses',0))+1
        rounds.append({'a':a['id'],'b':b['id'],'winner':winner['id'],'scores':[round(sa,2),round(sb,2)]})
    t['tournaments'].append({'day':day,'rounds':rounds,'rule':'earned performance only'}); t['tournaments']=t['tournaments'][-100:]
    save(FILES['tournaments'],t)
    return rounds
